### ISSUE TITLE
VM Summit at Node.js Interactive EU

### ISSUE THREAD

**Issue by mikeal** [nodejs/vm#3]
Heya,

We're doing a Collaborator Summit in Amsterdam after Node.js Interactive. It would be great to have another VM summit. I know a lot of the V8 team is in Munich so it would be great to get them to Interactive and the Collaborator Summit.

**Comment by jasnell** [comment]
Absolutely!

**Comment by ronkorving** [comment]
You should invite the Chakra team :)

**Comment by MylesBorins** [comment]
@nodejs/chakracore

**Comment by aruneshchandra** [comment]
@nodejs/chakracore  would love to participate!

**Comment by mhdawson** [comment]
- 1 from me as well.

**Comment by fhinkel** [comment]
Sounds great! Do we already have a few specific topics in mind we want to discuss?

**Comment by joshgav** [comment]
This is stale now so closing, see #6 for next VM Summit. Thanks!
