### ISSUE TITLE
VM Summit #3

### ISSUE THREAD

**Issue by aruneshchandra** [nodejs/vm#4]
At VM Summit 2 during Node Interactive Austin, we decided to meet again (end of feb / early march 2017) to evaluate the progress of ABI stable prototypes namely [NAPI](https://github.com/nodejs/abi-stable-node) and FFI and discuss including them in Node v8.0 as experimental. 

This onsite meeting is being planned to be held at the [_Microsoft campus in Redmond, WA_](https://www.google.com/maps/place/1+Microsoft+Way,+Redmond,+WA+98052/@47.6393261,-122.130572,17z/data=!3m1!4b1!4m5!3m4!1s0x54906d73f7de150b:0x922499d19305e9a0!8m2!3d47.6393225!4d-122.1283833). People will be able to participate online as well. 

Proposed Agenda:
* NAPI Demo by @mhdawson
* FFI Demo by @ofrobots
* Evaluate above stable ABI solutions to be included as experimental in Node v8.0 and older LTS versions
* Next steps (Documentation, support, bug fixes etc.)

Please respond to this poll to indicate your availability for VM Summit 3 
http://doodle.com/poll/qk4krgicifty24kk

The poll is to figure out the exact date for this meeting and also the headcount for onsite attendance.

**Comment by mikeal** [comment]
Is there a date associated with this?

In the future we may want to try and line these up with TC39 meetings since a few people will overlap.

**Comment by digitalinfinity** [comment]
@mikeal the doodle poll that @aruneshchandra linked to is to help figure out the date. The options are Feb 28 to Mar 3- these dates were picked with the idea that if we need a go/no go decision on ABI stable node as an experimental feature in Node v8.0, end of Feb/early march lines up with around when that branch will be created, and we should have a good idea around the state of the project (both NAPI and FFI) by then.

**Comment by mikeal** [comment]
Ah, solid reasoning, thanks @digitalinfinity :)

**Comment by aruneshchandra** [comment]
Updated the original comment for clarity around dates. Also to @mikeal's point going forward we should better align these meetings to avoid date conflicts and overlaps. This time its more tactical due to v8.0 release schedule.

**Comment by mcollina** [comment]
I would really like to join, the discussion at Node.js Interactive NA was really good and productive.

**Comment by aruneshchandra** [comment]
@mcollina please take this poll to indicate your participation preference http://doodle.com/poll/qk4krgicifty24kk

For now its looking like its going to be held at the Microsoft Redmond campus on Friday, March 3rd.

**Comment by mcollina** [comment]
@aruneshchandra when the final date will be announced?

**Comment by aruneshchandra** [comment]
I'm expecting a few more to respond to the poll - hopefully we will lock on the date by Friday Jan 20th and allow people to make travel arrangements in advance.

**Comment by aruneshchandra** [comment]
Based on the doodle poll - here's what the consensus was for the event:

**Date:** _Friday 3rd of March 2017_
**Time:** _9 AM to 4 PM_ 
**Location:** _Building 18 Microsoft Campus, Redmond WA_
_15701 NE 39th Street, Redmond, WA 98052_

**Comment by joshgav** [comment]
I'm taking notes here: https://docs.google.com/document/d/1mIYQ6YjI2yUS07h5dtkXW-EKgyY2_XYjgVFaZt0Yagk.

**Comment by ofrobots** [comment]
Link to FFI presentation https://docs.google.com/presentation/d/1rLBk9Erx1pbqLUBjcq_V2bLsiSxfPWT36dC0yLfFMOE/edit#slide=id.g19b3ce55c1_0_32

**Comment by aruneshchandra** [comment]
N-API Presentation deck
https://github.com/nodejs/abi-stable-node/blob/doc/VM%20Summit.pdf

**Comment by joshgav** [comment]
Notes: https://github.com/nodejs/abi-stable-node/pull/128

**Comment by joshgav** [comment]
also posted the notes to this repo in https://github.com/nodejs/vm/pull/5

**Comment by aruneshchandra** [comment]
This event is done. I wrote a blog capturing the high level discussion and next steps.
https://blogs.windows.com/msedgedev/2017/03/13/notes-from-nodejs-vm-summit/
