### ISSUE TITLE
VM Summit #4

### ISSUE THREAD

**Issue by dshaw** [nodejs/vm#6]
At [VM Summit #3](https://github.com/nodejs/vm/issues/4) hosted in Redmond, WA by Microsoft, we decided to meet again while most folks were in town for [Node Summit](http://nodesummit.com/) in San Francisco, CA.

The onsite meeting is being planned to be held at [NodeSource HQ](https://foursquare.com/v/nodesource-hq/57dc8296498ec3c9feef16f4). People will be able to participate online as well.

*Date:* Friday, July 28 2017
*Time:* 9 AM to Noon
*Location:* NodeSource HQ
577 2nd St (at Brannan St)
San Francisco, CA 94107

Proposed Agenda:

* N-API Update with @aruneshchandra and @mhdawson
* FFI Update with @ofrobots
* Resetting expectations and roadmap: What other VM-level initiatives do the [VM Working Group](https://github.com/nodejs/vm) want to work on? When we established this working group, we identified numerous opportunities to improve the contract between Node.js and JavaScript VM(s), however, we aligned on the highest impact functionality first with N-API and FFI. As those projects near completion, we want to make sure we prioritize our next steps.

RSVP: 

* https://doodle.com/poll/9cgcpqgeacxznab6
* Please RSVP by Friday, June 16th.

**Comment by cjihrig** [comment]
The date shouldn't be in March, right?

**Comment by aruneshchandra** [comment]
July 28th is after NodeSummit and is a Friday.

**Comment by dshaw** [comment]
July 28. Fixed.

**Comment by dshaw** [comment]
Given the maturity of N-API and the status of FFI, I think we can probably wrap up our meeting at Noon PT and then go out to lunch together. We definitely need to plan out our next steps and I expect that discussion to occupy most of our time.

I have created a Doodle for everyone. You can also use the Doodle to vote for a half day versus a all day session. Please RSVP by Friday, June 16th. 🙏

**Comment by dshaw** [comment]
Deadline is Friday, June 16th for those only following by email. 🌈🦄

**Comment by dshaw** [comment]
I'm looking forward to seeing everyone at Node Summit. Please RSVP, if you haven't already, so we can finalize headcount. https://doodle.com/poll/9cgcpqgeacxznab6

**Comment by rvagg** [comment]
Invites are going out to folks who put their names in the Doodle for the 28th of July, morning. If you're not on the list and you'd like to attend please let me know.

**Comment by aruneshchandra** [comment]
@rvagg Shu-yu from Mozilla will also be joining. I have sent you his contact over email.

**Comment by MylesBorins** [comment]
I think I missed signing up. Too late?

**Comment by rvagg** [comment]
@MylesBorins 👌

**Comment by rvagg** [comment]
@aruneshchandra @ofrobots @jasnell @mhdawson @digitalinfinity @jasongin @mcollina ... etc. there's 1/2 a day allocated for this, we have the following proposed agenda, is there anything else that we should put in to make the most of the time together?

* N-API Update with @aruneshchandra and @mhdawson
* FFI Update with @ofrobots
* Exploring future activities of the VM group

**Comment by aruneshchandra** [comment]
This is what I had shared earlier over email 

**N-API Update & Next Steps** 
•	Adoption efforts
•	Exit experimental status 
•	Enable N-API for async_hooks (async_hooks expert needed)
•	Take up a case study for Migrating NAN modules to N-API 
•	NAN Evolution 
•	Experiment: N-API port of Core modules  

**Other VM topics (time permitting)**
•	Inspector protocol 
•	Improving problem determination – debugging / tracing 
•	iOS and mobile scenario for Node

**Comment by mhdawson** [comment]
+1 on the list from @aruneshchandra as we discussed it earlier :)

**Comment by ofrobots** [comment]
@rvagg The PM for the V8 team, @thomasnat1 would like to be able to attend as well.

**Comment by rvagg** [comment]
Excellent! Sorry for the disconnect, I'm late to this particular party. I'll get that Agenda put in the invite and have requested that @thomasnat1 be invited too :+1:

**Comment by mcollina** [comment]
If there is some time and it is of interest to everyone, I would like to highlight some of the results from our research on Turbofan and current best practices in our codebase (from https://www.nearform.com/blog/node-js-is-getting-a-new-v8-with-turbofan/).

**Comment by jasongin** [comment]
I uploaded my slide deck to a gist, converted to markdown. It's about the N-API async hooks integration, fs core module conversion experiment, and VM diversity:

[Node VM Summit - N-API.md ](https://gist.github.com/jasongin/049d1ad6fbdf4c64ceafdfdfb202dc20)

Note this does not incorporate any feedback/discussion from the meeting. That should be captured in the google doc -- can someone share that link?

**Comment by orangemocha** [comment]
Is there a recording of the meeting? I couldn't find one on YouTube.

**Comment by jasnell** [comment]
The meet was in person and not recorded. I'll have the meeting notes available shortly.
