### ISSUE TITLE
nan-like shim for napi

### ISSUE THREAD

**Issue by mcollina** [nodejs/vm#7]
In order to foster the ecosystem to move from nan to napi, we need a shim layer for any Node.js runtime that does not include napi by default. Otherwise, it will take a very long time to ship modules with just napi, as it will become a valid approach after 6 goes unsupported.

**Comment by addaleax** [comment]
Have you seen https://github.com/nodejs/node-addon-api? It includes basically that, if I understand you correctly.

**Comment by mcollina** [comment]
Oh I completely missed that.
